version: '3.2'

services:
  backend_node:
    image: "node:14"
    volumes:
      - "./backend_node/:/home/node/app"
    expose:
      - "4000"
    command: bash -c "npm install && npm run dev"
    working_dir: /home/node/app
    ports:
      - 4000:4000
    links:
      - redis
    depends_on:
      - redis
    networks:
      - challenge

  frontend:
    image: "node:14"
    volumes:
      - "./frontend/:/home/node/front"
    expose:
      - "3000"
    command: bash -c "npm install && npm run docker"
    working_dir: /home/node/front
    environment:
      HOST: 0.0.0.0
    ports:
      - 3000:3000
    links:
      - backend_node
    depends_on:
      - backend_node
    networks:
      - challenge

  redis:
    image: redis
    ports:
      - 6379:6379
    expose:
      - "6379"
    volumes:
      - redis:/data
    networks:
      - challenge


networks:
  challenge:
    driver: bridge

volumes:
  redis:

